apps/faq/urls.py
from django.urls import path

from faq.views import FAQListView, FAQAddView, FAQEditView

app_name = 'faq'
urlpatterns = [
    path('faqs', FAQListView.as_view(), name='faqs'),
    path('faq', FAQAddView.as_view(), name='faq_add'),
    path('faq/<str:faq_id>', FAQEditView.as_view(), name='faq_edit'),
]

apps/package/urls.py
from django.urls import path

from package.views import IndexView, ReadersView, RVersionAddView, RVersionEditView, ReaderVersionsView, ReaderRVersionsView, RVersionStateView, PackagesView, PackagesInfoView, PackageAddView, PackageEditView

app_name ='package'
urlpatterns = [
    # 主页
    path('index', IndexView.as_view(), name='index'),
    # 添加阅读器号，以及返回所有的阅读器号信息
    path('readers', ReadersView.as_view(), name='readers'),
    # 添加阅读器新版本
    path('rversion', RVersionAddView.as_view(), name='rversion_add'),
    # 修改阅读器版本
    path('rversion/rv_<str:rv_id>', RVersionEditView.as_view(), name='rversion_edit'),
    # 同步更新阅读器版本
    path('rversion/state', RVersionStateView.as_view(), name='rv_state'),
    # 返回当前阅读器所有的已同步更新的版本号，依赖版本
    path('reader_<str:reader_id>/rversions/versions', ReaderVersionsView.as_view(), name='versions'),
    # 返回当前阅读器所有的已同步更新的所有版本的所有信息，历史版本
    path('reader_<str:reader_id>/rversions', ReaderRVersionsView.as_view(), name='rversions'),

    # 所有的升级包展示
    path('pid_<str:pid>/packages', PackagesView.as_view(), name='packages'),

    # 添加升级包版本
    path('pid_<str:pid>/package', PackageAddView.as_view(), name='pack_add'),
    # 对某个版本升级包的处理
    path('pid_<str:pid>/package/pack_<str:pack_id>', PackageEditView.as_view(), name='pack_edit'),
    # 提供对应rversion所有的包
    path('packages', PackagesInfoView.as_view(), name='packages_info'),
]

apps/user/urls.py
from django.urls import path

from apps.user.views import LoginView, LogoutView

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

guowen/urls.py
from django.contrib import admin
from django.urls import path, include
from package.views import get_package_test
from package.views import get_package, upload_pack


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('pack/', include('package.urls', namespace='pack')),
    path('faq/', include('faq.urls', namespace='faq')),
    path('tinymce/', include('tinymce.urls')),
    path('pack_test', get_package_test),
    path('pack', get_package),
    path('upload', upload_pack),
    path('', include('user.urls')),
]

ota/urls.py
from django.contrib import admin
from django.urls import path, include
from package.views import get_package_test, upload_pack, upload_pack_test
from general_user.views import get_package
from user.views import LoginView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='userview')),
    path('pack/', include('package.urls', namespace='pack')),
    path('faq/', include('faq.urls', namespace='faq')),
    path('tinymce/', include('tinymce.urls')),
    path('pack_test', get_package_test),
    path('pack', get_package),
    # 将原有的包文件同步到oss中
    path('upload_pack', upload_pack),
    path('upload_pack_test', upload_pack_test),
    path('android/', include('apps.update.urls',namespace='update')),
    path('', LoginView.as_view()),
]

apps/faq/models.py
from utils.db.base_db import BaseModel
from django.db import models
from tinymce.models import HTMLField

state = (
    (0, "未删除"),
    (1, "已删除")
)


class FAQ(BaseModel):
    question = models.CharField(max_length=124, verbose_name='问题')
    answer = HTMLField(verbose_name='解答')
    state = models.IntegerField(choices=state, default=0, verbose_name='问题状态')

    class Meta:
        db_table = 'faq'
        verbose_name = '问题'
        verbose_name_plural = verbose_name

apps/faq/views.py
import logging

from django.shortcuts import render
from django.views import View
from django.http.response import JsonResponse
from django.http import QueryDict
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from utils.decorator import is_login
from ota.response_code import CODE
from faq.models import FAQ
from faq.constants import FAQ_STATE

logger = logging.getLogger('ota')


class FAQListView(View):
    @method_decorator(login_required)
    def get(self, request):
        # 获取所有的未删除的faq
        faq_objs = FAQ.objects.filter(state=FAQ_STATE['ADD'])

        context = {
            "faq_objs": faq_objs
        }

        return render(request, 'faqs.html', context)


class FAQAddView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'faqadd.html')

    @method_decorator(is_login)
    def post(self, request):
        # 获取数据
        question = request.POST.get('question')
        anwser = request.POST.get('answer')

        if not all([question, anwser]):
            content = {
                "code": CODE.PARAMERR,
                "msg": "缺少参数"
            }
            return JsonResponse(content)

        # 业务处理
        try:
            faq_obj = FAQ()
            faq_obj.question = question
            faq_obj.answer = anwser
            faq_obj.save()
        except Exception as e:
            logger.error("添加问题失败, detail:{}".format(e))
            content = {
                "code": CODE.DBERR,
                "msg": "添加失败"
            }
            return JsonResponse(content)

        content = {
            "code": CODE.OK,
            "msg": "添加成功"
        }
        return JsonResponse(content)


# FAQ edit
class FAQEditView(View):
    @method_decorator(login_required)
    def get(self, request, faq_id):
        # 获取数据
        faq_id = faq_id

        # 获取对应faq对象
        faq_obj = FAQ.objects.filter(id=faq_id).first()

        # 判断是否存在
        if not faq_obj:
            content = {
                "code": CODE.PARAMERR,
                "msg": "请求faq对象不存在"
            }
            return JsonResponse(content)

        context = {
            "faq_obj": faq_obj
        }

        return render(request, 'faqedit.html', context)

    @method_decorator(is_login)
    def put(self, request, faq_id):

        # 获取数据
        faq_id = faq_id
        PUT = QueryDict(request.body)
        question = PUT.get('question')
        answer = PUT.get('answer')
        print(answer)
        # 检验参数会否完整
        if not all([question]):
            content = {
                "code": CODE.PARAMERR,
                "msg": "缺少参数"
            }
            return JsonResponse(content)

        faq_obj = FAQ.objects.filter(id=faq_id).first()

        try:
            faq_obj.question = question
            faq_obj.answer = answer
            faq_obj.save()
        except Exception as e:
            logger.error("修改失败 detail：{}".format(e))
            content = {
                "code": CODE.DBERR,
                "msg": "修改失败"
            }
            return JsonResponse(content)

        content = {
            "code": CODE.OK,
            "msg": '修改成功'
        }
        return JsonResponse(content)

    @method_decorator(is_login)
    def delete(self, request, faq_id):
        faq_id = faq_id

        faq_obj = FAQ.objects.filter(id=faq_id).first()

        if not faq_obj:
            content = {
                "code": CODE.PARAMERR,
                "msg": "错误的请求"
            }
            return JsonResponse(content)

        try:
            faq_obj.state = FAQ_STATE['DELETE']
        except Exception as e:
            logger.error("faqid:{}删除失败, detail:{}".format(faq_id, e))
            content = {
                "code": CODE.DBERR,
                "msg": "删除失败"
            }
            return JsonResponse(content)

        content = {
            "code": CODE.OK,
            "msg": "删除成功"
        }
        return JsonResponse(content)

apps/package/views.py
import logging

from multiprocessing.dummy import Pool
from urllib.parse import urlsplit

import requests
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import QueryDict
from django.http.response import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.db import transaction

from ota.response_code import CODE
from package.models import Reader, RVersion, Package
from utils.common_func.package import file_md5, fill_version, fill_package
from utils.decorator import is_login
from utils.oss import LocalOSS
from package.constants import RV_STATE, PACK_STATE
from package.sql import *


logger = logging.getLogger("ota")


def get_update_versions(reader_id):
    # 返回对应阅读器号的所有已同步更新版本号

    version_list = []
    version_objs = RVersion.objects.raw(test_order_update_rv, [reader_id, RV_STATE['UPDATE']])
    for version_obj in version_objs:
        version_list.append([version_obj.id, version_obj.version])
    return version_list


class IndexView(View):
    @method_decorator(login_required)
    def get(self, request):

        # 获取所有未删除的阅读器号的最新版本对象
        rv_objs = RVersion.objects.raw(test_each_newest_rvs)

        rv_list = []
        # 构建数据
        for rv_obj in rv_objs:
            reader_name = Reader.objects.filter(id=rv_obj.reader_id).first().reader_name

            dic = {'reader_id': rv_obj.reader_id,
                   'reader_name': reader_name,
                   'version': rv_obj.version,
                   'title': rv_obj.title,
                   'description': rv_obj.description,
                   'id': rv_obj.id,
                   'state': rv_obj.state,
                   'update_time': rv_obj.update_time
                   }

            rv_list.append(dic)
        return render(request, 'index.html', {'rv_list': rv_list})


class ReadersView(View):
    @method_decorator(is_login)
    def get(self, request):
        '''返回所有的阅读器号'''
        reader_list = []
        readers = Reader.objects.all()
        for i in readers:
            reader_list.append([i.id, i.reader_name])
        content = {
            "code": CODE.OK,
            "msg": 'success',
            "data": {
                "readers": reader_list
            }
        }
        return JsonResponse(content)

    @method_decorator(is_login)
    def post(self, request):
        '''添加阅读器号'''

        # 1、获取数据
        reader_name = request.POST.get('reader_name')

        # 2、校检数据完整性
        if not all([reader_name]):
            content = {
                "code": CODE.PARAMERR,
                "msg": "参数不完整",
            }
            return JsonResponse(content)

        # 校检阅读器型号是否已存在
        reader = Reader.objects.filter(reader_name=reader_name)
        if reader.exists():
            content = {
                "code": CODE.PARAMERR,
                "msg": "添加的阅读器型号已存在",
            }
            return JsonResponse(content)

        # 3、添加
        try:
            reader = Reader()
            reader.reader_name = reader_name
            reader.save()
            reader.sort = reader.id
            reader.save()
        except Exception as e:
            logger.error("{}添加失败 detail:{}".format(reader_name, e))
            content = {
                "code": CODE.DBERR,
                "msg": "添加失败"
            }
            return JsonResponse(content)

        content = {
            "code": CODE.OK,
            "msg": "添加成功"
        }
        return JsonResponse(content)


class RVersionAddView(View):
    @method_decorator(is_login)
    def post(self, request):
        '''添加阅读器的新版本'''

        # 获取数据
        reader_id = request.POST.get('reader_id')
        version = request.POST.get('version')
        title = request.POST.get('title')
        description = request.POST.get('description')
        depend_version = request.POST.get('depend_version')

        # 校检数据完整性
        if not all([reader_id, version]):
            content = {
                "code": CODE.PARAMERR,
                "msg": "参数不完整"
            }
            return JsonResponse(content)

        # 校检阅读器号是否存在,避免发布不存在的阅读器号的版本
        # 获取当前阅读器号未删除的所有对象
        reader = Reader.objects.filter(id=reader_id).first()
        if not reader:  # 不存在阅读器号
            content = {
                "code": CODE.PARAMERR,
                "msg": '阅读器号不存在'
            }
            return JsonResponse(content)

        # 获取当前阅读器号对应的所有对象
        rversions = RVersion.objects.filter(reader_id=reader_id)
        if rversions.exists():
            # 校验阅读器号的当前版本是否存在，避免发布阅读器号已经存在的版本
            rv_obj = rversions.filter(version=version)
            if rv_obj.exists():  # 当前阅读器的当前版本已存在
                content = {
                    "code": CODE.PARAMERR,
                    "msg": '当前阅读器号的当前版本已存在'
                }
                return JsonResponse(content)

            # 校验阅读器版本是否低于已发布的版本，只有高版本才能发布
            max_rv_obj = RVersion.objects.raw(test_newest_rv, [reader_id])[0]
            max_vcode = max_rv_obj.vcode

            # 当前版本小于最大版本
            if fill_version(version) < max_vcode:
                content = {
                    "code": CODE.PARAMERR,
                    "msg": '最新发布的版本不能小于已发布的版本'
                }
                return JsonResponse(content)

            if max_rv_obj.state == RV_STATE['ADD']:  # 当前版本号大于已发布但是未同步更新的版本号
                content = {
                    "code": CODE.PARAMERR,
                    "msg": '该阅读器号存在已发布未同步更新的版本'
                }
                return JsonResponse(content)

            # 将最新的版本的所有升级包信息加入到新建版本中,如果有依赖版本,就只添加大于等于依赖版本对应基础版本的升级包信息
            # 如果有依赖版本
            if depend_version not in ('0', None):
                depend_base_version = depend_version.split('.')[0]+'.0'
                pack_objs = Package.objects.raw(test_get_rv_gte_depend_package, [max_rv_obj.id, fill_package(depend_base_version)])
            else:
                pack_objs = Package.objects.filter(pid=max_rv_obj.id)
            try:
                new_rv_obj = RVersion()
                new_rv_obj.reader_id = reader_id
                new_rv_obj.version = version
                new_rv_obj.title = title
                new_rv_obj.description = description
                new_rv_obj.depend_version = depend_version
                new_rv_obj.sort = reader.sort
                new_rv_obj.save()
                for pack_obj in pack_objs:
                    new_pack_obj = Package()
                    new_pack_obj.base_version = pack_obj.base_version
                    new_pack_obj.model = pack_obj.model
                    new_pack_obj.pack = ''
                    new_pack_obj.md5 = ''
                    new_pack_obj.pid = new_rv_obj.id
                    new_pack_obj.state = pack_obj.state
                    new_pack_obj.save()
            except Exception as e:
                logger.error('{}{}发布失败,detail:{}'.format(reader_id, version, e))
                content = {
                    "code": CODE.DBERR,
                    "msg": "发布失败"
                }
                return JsonResponse(content)

        else:
            try:
                new_rv_obj = RVersion()
                new_rv_obj.reader_id = reader_id
                new_rv_obj.version = version
                new_rv_obj.title = title
                new_rv_obj.description = description
                new_rv_obj.depend_version = depend_version
                new_rv_obj.sort = reader.sort
                new_rv_obj.save()
            except Exception as e:
                logger.error('{}{}发布失败,detail:{}'.format(reader_id, version, e))
                content = {
                    "code": CODE.DBERR,
                    "msg": "发布失败"
                }
                return JsonResponse(content)

        content = {
            "code": CODE.OK,
            "msg": '发布成功'
        }

        return JsonResponse(content)


class RVersionEditView(View):
    @method_decorator(login_required)
    def get(self, request, rv_id):
        '''编辑页面'''
        # 获取数据
        rv_id = rv_id

        # 校检数据
        if not all([rv_id]):
            content = {
                "code": CODE.PARAMERR,
                "msg": "参数不完整"
            }
            return JsonResponse(content)

        # 当前阅读器对应的queryset对象
        rv_obj = RVersion.objects.filter(id=rv_id).first()
        reader_id = rv_obj.reader_id
        version_list = get_update_versions(reader_id)

        rv_obj.reader_name = Reader.objects.filter(id=reader_id).first().reader_name

        # 构造数据
        context = {
            'rv_obj': rv_obj,
            'versions': version_list
        }
        return render(request, 'rversion.html', context)

    @method_decorator(is_login)
    def put(self, request, rv_id):
        '''修改操作'''
        # 获取数据
        PUT = QueryDict(request.body)
        reader_id = PUT.get("reader_id")
        version = PUT.get("version")
        title = PUT.get('title')
        description = PUT.get('description')
        depend_version = PUT.get('depend_version')

        # 校检参数完整性
        if not all([reader_id, version]):
            content = {
                "code": CODE.PARAMERR,
                "msg": "参数不完整"
            }
            return JsonResponse(content)

        # 校验阅读器号的当前版本是否存在
        rv_obj = RVersion.objects.filter(id=rv_id).first()
        if not rv_obj:
            content = {
                "code": CODE.PARAMERR,
                "msg": '当前版本不存在'
            }
            return JsonResponse(content)

        # 校验当前提交版本是否低于已同步更新最高版本
        max_rv_obj = RVersion.objects.raw(test_order_update_rv, [reader_id, RV_STATE['UPDATE']])[0]
        max_vcode = max_rv_obj.vcode

        # 当前版本小于最大版本
        if fill_version(version) < max_vcode:
            content = {
                "code": CODE.PARAMERR,
                "msg": '发布版本不能小于已同步更新的版本'
            }
            return JsonResponse(content)

        try:

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% block load %}
{% load static from staticfiles %}
{% endblock %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block top-title %}
        当当国文阅读器更新包
        {% endblock %}
    </title>
    <link href="{% static 'css/reset.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/func.js' %}"></script>

    {% block link %}

    {% endblock %}
</head>

<body>
    <div class="page">
        <div class="top_bar">
            <div class="title fl">
                <h1>
                    当当国文电子阅读器软件更新
                </h1>
            </div>
            <div class="login fr">
                {% if request.user.is_authenticated %}
                欢迎您&nbsp;{{ request.user.username }} |
                <a id="logout" href="{% url 'userview:logout' %}">退出</a>
                {% endif %}
            </div>
        </div>
        {% block main %}
        <div class="main">
        </div>
        {% endblock %}
    </div>
</body>

</html>

templates/faqadd.html
{% extends 'base.html' %}

{% block load %}
{% load static from staticfiles %}
{% endblock %}

{% block link %}
<link href="{% static 'css/faq.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/faqadd.js' %}"></script>
<script src="{% static 'js/tiny_mce_src.js' %}"></script>
<script type="text/javascript">
    tinyMCE.init({
        'mode': 'textareas',
        'theme': 'simple',
        'language': 'zh-cn',
        'width': 400,
        'height': 100
    });
</script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="faq-edit-header">
        <div class="tips fl">
            faq编辑
        </div>
    </div>
    <div class="faq-edit-info">
            <ul>
                {% csrf_token %}
                <li>
                    <label>问题</label><input type="text" id="question" name="question">
                </li>
                <li>
                    <label>解答</label><textarea name="answer" id="answer"></textarea>
                </li>
            </ul>
            <div class="faq-sub">
                <label>&nbsp;</label>
                <input type="submit" id="faq_sub" value="提交">
            </div>
    </div>
</div>
{% endblock %}

templates/faqedit.html
{% extends 'base.html' %}

{% block load %}
{% load static from staticfiles %}
{% endblock %}

{% block link %}
<link href="{% static 'css/faq.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/faqedit.js' %}"></script>
<script src="{% static 'js/tiny_mce_src.js' %}"></script>
<script type="text/javascript">
    tinyMCE.init({
        'mode': 'textareas',
        'theme': 'simple',
        'language': 'zh-cn',
        'width': 400,
        'height': 100
    });
</script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="faq-edit-header">
        <div class="tips fl">
            faq编辑
        </div>
    </div>
    <div class="faq-edit-info">
            <ul>
                {% csrf_token %}

                <li>
                    <input type="hidden" id="faq_id" value="{{ faq_obj.id }}" />
                    <label>问题</label><input type="text" id="question" name="question" value="{{ faq_obj.question }}">
                </li>
                <li>
                    <input type="hidden" id="answer_tmp" value="{{ faq_obj.answer }}">
                    <label>解答</label><textarea name="answer" id="answer"></textarea>
                </li>
            </ul>
            <div class="faq-sub">
                <label>&nbsp;</label>
                <input type="submit" id="faq_sub" value="提交">
            </div>
    </div>
</div>
{% endblock %}

templates/history.html
{% extends 'base.html' %}

{% block load %}
{% load static from staticfiles %}
{% endblock %}

{% block link %}
<link href="{% static 'css/history.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/history.js' %}"></script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="detail">
        {% for rversion in rversions %}
        <ul>
            <li>
                <h2>{{ reader_name }}{{ rversion.reader_name }}{{ rversion.version }}&nbsp;:&nbsp;{{ rversion.update_time|date:'Y/m/d H:i:s' }}更新内容如下</h2>
            </li>
            <li>{{ rversion.description|safe }}</li>
            <input type="hidden" id="rv_id" value="{{ rversion.id }}" />
            <li><a id="package" href="javascript:void(0)">查看软件包</a></li>
        </ul>
        {% endfor %}
    </div>
    <div class="pop-shadow"></div>
        <div class="pop-main" id="pop">
        <div class="pop-con">
            <div class="pop-title" id="pop-title">
                <h3>查看软件包</h3>
            </div>
            <span class="close-ico"><a href="javascript:;"></a></span>
            <div id="forscroll">
                <div class="pack-table">
                    <table>
                        <thead>
                            <tr>
                                <th width="10%">基础版本</th>
                                <th width="10%">硬件版本</th>
                                <th width="35%">链接地址</th>
                                <th width="35%">md5地址</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>

            </div>
            </div>

        </div>
    </div>

</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block load %}
{% load static from staticfiles %}
{% endblock %}

{% block link %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/sha1.min.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

{% block main %}
<div class="main clearfix">
    <div class="main-login clearfix">
        <div class="login-border clearfix">
            <div class="tips">
                <h1>当当国文阅读管理系统</h1>
            </div>
            <div class="login-form clearfix">
                <form action="{% url 'userview:login' %}" method="POST" class="form-login">
                    {% csrf_token %}
                    <div class="username">
                        <label class="fl">账&nbsp;号:</label><input type="text" id="username" name="username" class="fr" autocomplete="true"><br>
                    </div>
                    <div class="passwd">
                        <label class="fl">密&nbsp;码:</label><input type="password" id="passwd" name="passwd" class="fr" autocomplete="true"><br>
                    </div>
                    <div class="error-msg" id="error-msg"><p>&nbsp;</p></div>
                    <div class="submit">
                        <input type="submit" value="登录">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/mainpage.html
{% extends 'base.html' %}

{% block load %}
{% load static from staticfiles %}
{% endblock %}

{% block link %}
    <link href="{% static 'css/mainpage.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/option.js' %}"></script>
{% endblock %}


{% block main %}
<div class="main" clearfix>
    <div class="mainpage sty" clearfix>
        <div class="option" clearfix>
            <div class="versionmanage" clearfix>
                <input type="button" onclick="versionmanagehandle()" value="管理版本">
            </div>
            <div class="versionpublish" clearfix>
                <input type="button" onclick="versionpublishhandle()" value="正式版本">
            </div>
            <div class="publishtest" clearfix>
                <input type="button" onclick="publishtesthandle()" value="升级测试">
            </div>
        </div>
        {% block displayarea %}
        <div class="displayarea">
            <p>这里是功能请求后显示区域</p>
        </div>
        {% endblock %}
    </div>
</div>

{% endblock %}

templates/packages.html
{% extends 'base.html' %}

{% block load %}
{% load static from staticfiles %}
{% endblock %}

{% block link %}
<link href="{% static 'css/packages.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/packages.js' %}"></script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="edit-header">
        <div class="tips fl">
            测试库更新包数据列表
            <span style="color:red;">（以下列表中存在需要上传的更新时点击编辑更新软件包即可!）</span>
        </div>
        <div class="add-pack fl">
            <a href="{% url 'pack:pack_add' pid=pid %}">添加</a>
        </div>
    </div>
    <div class="pack-table">
        {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <th width="10%">基础版本</th>
                    <th width="10%">硬件版本</th>
                    <th width="35%">链接地址</th>
                    <th width="35%">md5地址</th>
                    <th width="10%">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for pack_obj in pack_objs %}
                <tr>
                    <td>{{ pack_obj.base_version }}</td>
                    <td>{{ pack_obj.model }}</td>
                    <td>{{ pack_obj.pack }}</td>
                    <td>{{ pack_obj.md5 }}</td>
                    <td>
                        <a href="javascript:;" pid="{{ pack_obj.pid }}" pack_id="{{ pack_obj.id }}" id="pack_edit">编辑</a>
                        <a href="javascript:;" id="pack_del" style="color: red">删除</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/rversion.html
{% extends 'base.html' %}

{% block load %}
{% load static from staticfiles %}
{% endblock %}

{% block link %}
<link href="{% static 'css/rversion.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/tiny_mce_src.js' %}"></script>
<script src="{% static 'js/rversion.js' %}"></script>
<script type="text/javascript">
    tinyMCE.init({
        'mode': 'textareas',
        'theme': 'simple',
        'language': 'zh-cn',
        'width': 400,
        'height': 100
    });
</script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="rversion-edit-header">
        <div class="tips fl">
            当当国文阅读器更新信息
            <span style="color:red;">（提交前请先更新软件包）</span>
        </div>
        <div class="func fr">
            <div class="pack-list fl">
                <a href="{% url 'pack:packages' pid=rv_obj.id %}">软件包列表</a>
            </div>
            <div class="history fr">
                <a href="{% url 'pack:rversions' reader_id=rv_obj.reader_id %}">查看历史版本</a>
            </div>
        </div>
    </div>
    <div class="rversion-edit-info">
        {% csrf_token %}
        <ul>
            <li>
                <label>阅读器号</label>
                <input type="hidden" value="{{ rv_obj.id }}" id="rv_id">
                <input type="hidden" value="{{ rv_obj.reader_id }}">
                <input type="text" id="reader_name" name="reader_name" value="{{ rv_obj.reader_name }}"
                    readonly="readonly">
            </li>
            <li>
                <label>版本号</label><input name="version" id="version" value="{{ rv_obj.version }}" type="text">
            </li>
            <li>
                <label>标题</label><input name="v-title" id="v-title" value="{{ rv_obj.title }}" type="text">
            </li>
            <li>
                <input type="hidden" id="textarea_tmp" value="{{ rv_obj.description }}" />
                <label>描述</label><textarea name="v-description" id="description"></textarea>
            </li>
            <li>
                <label>依赖版本</label>
                <select name="depend-version" id="depend_version">
                    <option value="0">--无--</option>
                    {% for version in versions %}
                        {% if version.1 == rv_obj.depend_version %}
                            <option value="{{ version.1 }}" selected>{{ version.1 }}</option>
                        {% else %}
                            <option value={{ version.1 }}>{{ version.1 }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </li>
        </ul>
        <div class="rversion-sub">
            <label>&nbsp;</label>
            <input type="button" id="rversion_sub" value="提交">
        </div>
    </div>
</div>
{% endblock %}